name: "Labeler: Cache Retention"

on:
  schedule:
    - cron: "36 4 * * *" # 4:36 every day (arbitrary time daily)

  workflow_dispatch:

jobs:
  cache-retention:
    # Do not run the workflow on forks outside the 'jeffhandley' org
    if: ${{ github.repository_owner == 'jeffhandley' }}
    uses: jeffhandley/github-ml-labeler/.github/workflows/cache-retention.yml@main
