name: "Labeler: Build Predictor App"

on:
  # Allow dispatching the workflow via the Actions UI
  workflow_dispatch:
    inputs:
      rebuild:
        description: "Force a rebuild of the app"
        type: boolean

jobs:
  build-predictor:
    permissions:
      actions: write
    uses: jeffhandley/github-ml-labeler/.github/workflows/build-predictor.yml@main
    with:
      rebuild: ${{ inputs.rebuild }}
