name: "Labeler: Predict Pull Label"

on:
  pull_request:
    types: [opened, edited, synchronize]

  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        type: number
        required: true
      label_prefix:
        description: "Label Prefix"
        type: string
        default: "area-"
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: "0.75"
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        type: string
        default: "needs-area-label"
      model_cache_key:
        description: "The optional cache key suffix to use for saving the model (defaults to repository name)"
        type: string

jobs:
  label-pull:
    permissions:
      pull-requests: write
    uses: jeffhandley/github-ml-labeler/actions/labeler-predict-pull.yml@main
    with:
      number: ${{ fromJSON( inputs.number || github.event.number ) }}
      label_prefix: ${{ inputs.label_prefix || 'area-' }}
      threshold: ${{ fromJSON( inputs.threshold || 0.75 ) }}
      default_label: ${{ inputs.default_label || 'needs-area-label' }}
      model_cache_key: ${{ inputs.model_cache_key || github.repository }}
