name: "Labeler: Promote Model"

on:
  workflow_dispatch:
    inputs:
      promote_issues:
        description: "Promote Issues Model"
        type: choice
        options:
          - Yes
          - No
        default: 'Yes'
        required: true
      promote_pulls:
        description: "Promote Pulls Model"
        type: choice
        options:
          - Yes
          - No
        default: 'Yes'
        required: true
      model_cache_key:
        description: "The cache key suffix to promote"
        type: string
        default: 'staging'
        required: true
      backup_cache_key:
        description: "The cache key suffix to use for backing up the currently promoted model"
        type: string
        required: true
        default: "backup"

permissions:
  actions: write

jobs:
  labeler-promote-issues:
    if: ${{ inputs.promote_issues == 'Yes' }}
    uses: jeffhandley/github-ml-labeler/.github/workflows/promote-issues.yml@main
    with:
      model_cache_key: ${{ inputs.model_cache_key }}
      backup_cache_key: ${{ inputs.backup_cache_key }}

  labeler-promote-pulls:
    if: ${{ inputs.promote_pulls == 'Yes' }}
    uses: jeffhandley/github-ml-labeler/.github/workflows/promote-pulls.yml@main
    with:
      model_cache_key: ${{ inputs.model_cache_key }}
      backup_cache_key: ${{ inputs.backup_cache_key }}
