name: "Labeler: Promote Issue Model"

on:
  workflow_dispatch:
    inputs:
      model_cache_key:
        description: "The cache key suffix to promote"
        type: string
        required: true
      backup_cache_key:
        description: "The cache key suffix to use for backing up the currently promoted model"
        type: string
        required: true
        default: "backup"

jobs:
  promote-issue-model:
    permissions:
      actions: write
    uses: jeffhandley/github-ml-labeler/actions/labeler-promote-issues.yml@main
    with:
      model_cache_key: ${{ inputs.model_cache_key }}
      backup_cache_key: ${{ inputs.backup_cache_key }}
