name: "Labeler: Predict Issue Labels"

on:
  workflow_call:
    inputs:
      issue_numbers:
        description: "Issue Numbers"
        type: string
        required: true
      label_prefix:
        description: "Label Prefix"
        type: string
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        type: string
      model_cache_key:
        description: "The optional cache key suffix to use for loading the model (defaults to repository name)"
        type: string

permissions:
  issues: write

env:
  MODEL_PATH: labeler-cache/issue-model.zip
  MODEL_CACHE_KEY: github-ml-labeler/issues/model/${{ inputs.model_cache_key || github.repository }}

jobs:
  predict-issues:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the 'jeffhandley/github-ml-labeler' repo"
        uses: actions/checkout@v4
        with:
          repository: jeffhandley/github-ml-labeler

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: "Restore model from cache"
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.MODEL_PATH }}
          key: ${{ env.MODEL_CACHE_KEY }}
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run Predictor"
        run: |
          dotnet run -c Release --project src/Predictor -- \
            ${{ format('--token "{0}"', secrets.GITHUB_TOKEN) }} \
            ${{ format('--repo "{0}"', github.repository) }} \
            ${{ format('--issue-model "{0}"', env.MODEL_PATH) }} \
            ${{ format('--issue-numbers "{0}"', inputs.issue_numbers) }} \
            ${{ format('--label-prefix "{0}"', inputs.label_prefix) }} \
            ${{ format('--threshold {0}', inputs.threshold) }} \
            ${{ inputs.default_label && format('--default-label "{0}"', inputs.default_label) }}
